### ISSUE TITLE
[EPIC] Subscriptions

### ISSUE THREAD

**Issue by heimdallrhg** [akuru-io/central#2]
- [ ] Users should able to request subscription key from the website or any other platform
  - [ ] Users will receive subscription keys via email
  - [ ] `GET /subscription` - generate subscription key (JWT Token)
  Inputs: `email *` `firstName` `lastName` `organisation` `nosOfClients (default: 1)`
- They can redeem their keys using `Akuru Client` installed in there workstations
  - [ ] `POST /subscription` - redeem
  Parameters: `client identifier` `userAgent`
