### ISSUE TITLE
[EPIC] FONTS GALLERY

### ISSUE THREAD

**Issue by heimdallrhg** [akuru-io/central#3]
- [ ] List all the fonts in the Feed on Client App
  - [ ] Free fonts default, and premium fonts based on subscription
- [ ] List all the fonts in the Feed on Web Portal
  - [ ] Free fonts default, and premium fonts based on subscription
