### ISSUE TITLE
[EPIC] INSTALL, UNINSTALL, UPDATE AND RESET FONTS-CACHE

### ISSUE THREAD

**Issue by heimdallrhg** [akuru-io/central#4]
- [ ] Should able to install, uninstall, Update and Reset Font Cache using CLI
- [ ] Should be able to call CLI from Client
- [ ] Should verify `install` command via API for valid subscription
